# supervised machine learning: logistic regression

# Absenteeism at work

### Import the libraries

In [1]:
import numpy as np
import pandas as pd

### load the data

In [2]:
data_preprocessed=pd.read_csv('Absenteeism_preprocessed.csv')
data_preprocessed.head()

,Reason1,Reason2,Reason3,Reason4,Month value,Day of the week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2

### create the targets

In [3]:
#find median of the absenteeism time in hours to devide data into two classes either o or 1
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [4]:
#since median is 3.0, anyone above 3hr is excessively absent(1) and below is moderately absent(0)
# in supervised learning these 0 and 1 called as: TARGETS

targets=np.where(data_preprocessed['Absenteeism Time in Hours']>3,1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [5]:
data_preprocessed['Excessive absenteeism']=targets

In [6]:
data_preprocessed.head()

,Reason1,Reason2,Reason3,Reason4,Month value,Day of the week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Excessive absenteeism
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2,0
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4,1
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2,0

### a comment on targets

In [7]:
#using median as a cut off line is numerically stable and grid
#by setting the median we can implicitly balance the dataset
#roughly half of the data are 0 and other half are 1
#this will prevent our model from learning to output only 1 and only 0
#to prove that divide total no. of 1s by total no. of targets

In [8]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [9]:
#this means 46% of targets are 1 and 54% of targets are 0
#when balancing dataset, two classes needed represent 50%-50% of the sample exactly
#usually,60%-40% split will work for logistic regression but this is not true for other algorithms
#proceeding further as two classes are divided roughly equally.45-55split

In [10]:
#drop the absenteeism in hours column to avoid multi-collinearity
data_targets=data_preprocessed.drop(['Absenteeism Time in Hours','Day of the week','Distance to Work','Daily Work Load Average'],axis=1)
data_targets.head()

,Reason1,Reason2,Reason3,Reason4,Month value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Excessive absenteeism
0,0,0,0,1,7,289,33,30,0,2,1,1
1,0,0,0,0,7,118,50,31,0,1,0,0
2,0,0,0,1,7,179,38,31,0,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0,1
4,0,0,0,1,7,289,33,30,0,2,1,0

In [11]:
#is this a check point in other words..........
#is this new variable(data_targets) is pointing to same piece of memory as old variable(data_preprocessed)
#can check this by using reserved word "is"
#if the output is 'true' then two variables are refering to the same objects
#if the output is 'false' then two variables are refering to the different objects

In [12]:
data_preprocessed is data_targets

False

In [13]:
#this means refering two different objects so data_targets is the checkpoint.

### create checkpoint

In [14]:
data_with_targets = data_targets.copy()
data_with_targets.head()

,Reason1,Reason2,Reason3,Reason4,Month value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Excessive absenteeism
0,0,0,0,1,7,289,33,30,0,2,1,1
1,0,0,0,0,7,118,50,31,0,1,0,0
2,0,0,0,1,7,179,38,31,0,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0,1
4,0,0,0,1,7,289,33,30,0,2,1,0

### select the inputs for regression

In [15]:
data_with_targets.shape

(700, 12)

In [16]:
#pandas iloc method is used to select the inputs for regression
#pandas iloc method selects(slices) data by position when given rows and columns wanted

In [17]:
data_with_targets.iloc[:,0:14] #method1 for iloc indices selection

,Reason1,Reason2,Reason3,Reason4,Month value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Excessive absenteeism
0,0,0,0,1,7,289,33,30,0,2,1,1
1,0,0,0,0,7,118,50,31,0,1,0,0
2,0,0,0,1,7,179,38,31,0,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0,1
4,0,0,0,1,7,289,33,30,0,2,1,0
5,0,0,0,1,7,179,38,31,0,0,0,0
6,0,0,0,1,7,361,28,27,0,1,4,1
7,0,0,0,1,7,260,36,23,0,4,0,1
8,0,0,1,0,7,155,34,25,0,2,0,1
9,0,0,0,1,7,235,37,29,1,1,1,1
10,1,0,0,0,7,260,36,23,0,4,0,1
11,1,0,0,0,7,260,36,23,0,4,0,1
12,1,0,0,0,7,260,36,23,0,4,0,1
13,1,0,0,0,7,179,38,31,0,0,0,0
14,0,0,0,1,7,179,38,31,0,0,0,1
15,1,0,0,0,7,246,41,23,0,0,0,1
16,0,0,0,1,7,179,38,31,0,0,0,0
17,0,0,1,0,7,179,38,31,0,0,0,1
18,1,0,0,0,7,189,33,25,0,2,2,1
19,0,0,0,1,8,248,47,32,0,2,1,0
20,1,0,0,0,8,330,28,25,1,0,0,1
21,1,0,0,0,8,179,38,31,0,0,0,0
22,1,0,0,0,8,361,28,27,0,1,4,1
23,0,0,0,1,8,260,36,23,0,4,0,1
24,0,0,1,0,8,289,33,30,0,2,1,1
25,0,0,0,1,8,361,28,27,0,1,4,1
26,0,0,0,1,8,289,33,30,0,2,1,0
27,0,0,0,1,8,157,29,22,0,0,0,1
28,0,0,1,0,8,289,33,30,0,2,1,1
29,0,0,0,1,8,179,38,31,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,4,155,34,25,0,2,0,1
671,0,0,1,0,4,225,28,24,0,1,2,1
672,1,0,0,0,4,118,50,31,0,1,0,0
673,0,0,0,1,4,179,30,19,1,0,0,0
674,0,0,0,1,5,235,37,29,1,1,1,1
675,0,0,1,0,5,225,41,28,1,2,2,0
676,0,0,0,1,5,235,32,25,1,0,0,0
677,1,0,0,0,5,118,37,28,0,0,0,0
678,0,0,0,1,5,235,43,38,0,1,0,1
679,1,0,0,0,5,179,30,19,1,0,0,0
680,0,0,0,1,5,291,40,25,0,1,1,0
681,1,0,0,0,5,225,41,28,1,2,2,1
682,0,0,1,0,5,300,43,25,0,2,1,1
683,0,0,0,1,5,225,41,28,1,2,2,1
684,0,0,0,1,5,179,30,19,1,0,0,0
685,0,0,0,1,5,118,50,31,0,1,0,0
686,1,0,0,0,5,118,50,31,0,1,0,0
687,0,0,0,1,5,118,37,28,0,0,0,0
688,0,0,0,0,5,118,50,31,0,1,0,0
689,0,0,0,1,5,179,30,19,1,0,0,0
690,0,0,0,0,5,378,36,21,0,2,4,0
691,0,1,0,0,5,179,40,22,1,2,0,0
692,1,0,0,0,5,155,34,25,0,2,0,1
693,1,0,0,0,5,235,32,25,1,0,0,1
694,0,0,0,1,5,291,40,25,0,1,1,1
695,1,0,0,0,5,179,40,22,1,2,0,1
696,1,0,0,0,5,225,28,24,0,1,2,0
697,1,0,0,0,5,330,28,25,1,0,0,1
698,0,0,0,1,5,235,32,25,1,0,0,0
699,0,0,0,1,5,291,40,25,0,1,1,0

In [18]:
unscaled_inputs=data_with_targets.iloc[:,:-1] #method2 for iloc indices selection

In [19]:
unscaled_inputs.head()

,Reason1,Reason2,Reason3,Reason4,Month value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,0,0,0,1,7,289,33,30,0,2,1
1,0,0,0,0,7,118,50,31,0,1,0
2,0,0,0,1,7,179,38,31,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0
4,0,0,0,1,7,289,33,30,0,2,1

### standardize the data

In [20]:
# standardize the inputs

# standardization is one of the most common preprocessing tools
# since data of different magnitude (scale) can be biased towards high values,
# we want all inputs to be of similar magnitude
# this is a peculiarity of machine learning in general - most (but not all) algorithms do badly with unscaled data

# a very useful module we can use is StandardScaler 
# it has much more capabilities than the straightforward 'preprocessing' method
#from sklearn.preprocessing import StandardScaler


# we will create a variable that will contain the scaling information for this particular dataset
# here's the full documentation: http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

# define scaler as an object
#absenteeism_scaler = StandardScaler()

In [21]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [22]:
unscaled_inputs.columns.values

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [23]:
# check what are all columns that we've got
# choose the columns to scale
# we later augmented this code and put it in comments
# columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pets']
    
# select the columns to omit
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [24]:
# create the columns to scale, based on the columns to omit
# use list comprehension to iterate over the list
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [25]:
# declare a scaler object, specifying the columns you want to scale
absenteeism_scaler = CustomScaler(columns_to_scale)

In [26]:
#absenteeism_scaler is a empty standardscaler object
#absenteeism_scaler will be used to subtract the mean and divide by standard deviation variablewise(featurewise)
#next is fit the input data using fit method

In [27]:
absenteeism_scaler.fit(unscaled_inputs) 
#this will calculate and store mean and standard deviation

CustomScaler(columns=['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month value',
                      'Transportation Expense', 'Age', 'Body Mass Index',
                      'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [28]:
#whenever you get new data you will know that your standardization information ...
#...is contained in absenteeism_scaler

In [29]:
#scale the inputs using transform method

In [30]:
scaled_inputs=absenteeism_scaler.transform(unscaled_inputs)
#this operation will transform unscaled inputs using the info in absenteeism_scaler
#in simple words...it will subtract mean and divide by the standard deviation

In [31]:
scaled_inputs

,Reason1,Reason2,Reason3,Reason4,Month value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,-0.577350,-0.092981,-0.314485,0.821365,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
1,-0.577350,-0.092981,-0.314485,-1.217485,0.182726,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
2,-0.577350,-0.092981,-0.314485,0.821365,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
3,1.732051,-0.092981,-0.314485,-1.217485,0.182726,0.854936,0.405184,-0.643782,0,0.880469,-0.589690
4,-0.577350,-0.092981,-0.314485,0.821365,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
5,-0.577350,-0.092981,-0.314485,0.821365,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
6,-0.577350,-0.092981,-0.314485,0.821365,0.182726,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
7,-0.577350,-0.092981,-0.314485,0.821365,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
8,-0.577350,-0.092981,3.179797,-1.217485,0.182726,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
9,-0.577350,-0.092981,-0.314485,0.821365,0.182726,0.190942,0.091435,0.532229,1,-0.019280,0.268487
10,1.732051,-0.092981,-0.314485,-1.217485,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
11,1.732051,-0.092981,-0.314485,-1.217485,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
12,1.732051,-0.092981,-0.314485,-1.217485,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
13,1.732051,-0.092981,-0.314485,-1.217485,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
14,-0.577350,-0.092981,-0.314485,0.821365,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
15,1.732051,-0.092981,-0.314485,-1.217485,0.182726,0.356940,0.718933,-0.878984,0,-0.919030,-0.589690
16,-0.577350,-0.092981,-0.314485,0.821365,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
17,-0.577350,-0.092981,3.179797,-1.217485,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
18,1.732051,-0.092981,-0.314485,-1.217485,0.182726,-0.503235,-0.536062,-0.408580,0,0.880469,1.126663
19,-0.577350,-0.092981,-0.314485,0.821365,0.468236,0.387122,1.660180,1.237836,0,0.880469,0.268487
20,1.732051,-0.092981,-0.314485,-1.217485,0.468236,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690
21,1.732051,-0.092981,-0.314485,-1.217485,0.468236,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
22,1.732051,-0.092981,-0.314485,-1.217485,0.468236,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
23,-0.577350,-0.092981,-0.314485,0.821365,0.468236,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
24,-0.577350,-0.092981,3.179797,-1.217485,0.468236,1.005844,-0.536062,0.767431,0,0.880469,0.268487
25,-0.577350,-0.092981,-0.314485,0.821365,0.468236,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
26,-0.577350,-0.092981,-0.314485,0.821365,0.468236,1.005844,-0.536062,0.767431,0,0.880469,0.268487
27,-0.577350,-0.092981,-0.314485,0.821365,0.468236,-0.986140,-1.163560,-1.114186,0,-0.919030,-0.589690
28,-0.577350,-0.092981,3.179797,-1.217485,0.468236,1.005844,-0.536062,0.767431,0,0.880469,0.268487
29,-0.577350,-0.092981,-0.314485,0.821365,0.468236,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
...,...,...,...,...,...,...,...,...,...,...,...
670,-0.577350,-0.092981,-0.314485,0.821365,-0.673803,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
671,-0.577350,-0.092981,3.179797,-1.217485,-0.673803,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
672,1.732051,-0.092981,-0.314485,-1.217485,-0.673803,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
673,-0.577350,-0.092981,-0.314485,0.821365,-0.673803,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
674,-0.577350,-0.092981,-0.314485,0.821365,-0.388293,0.190942,0.091435,0.532229,1,-0.019280,0.268487
675,-0.577350,-0.092981,3.179797,-1.217485,-0.388293,0.040034,0.718933,0.297027,1,0.880469,1.126663
676,-0.577350,-0.092981,-0.314485,0.821365,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
677,1.732051,-0.092981,-0.314485,-1.217485,-0.388293,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
678,-0.577350,-0.092981,-0.314485,0.821365,-0.388293,0.190942,1.032682,2.649049,0,-0.019280,-0.589690
679,1.732051,-0.092981,-0.314485,-1.217485,-0.388293,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
680,-0.577350,-0.092981,-0.314485,0.821365,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487
681,1.732051,-0.092981,-0.314485,-1.217485,-0.388293,0.040034,0.718933,0.297027,1,0.880469,1.126663
682,-0.577350,-0.092981,3.179797,-1.217485,-0.388293,1.171843,1.032682,-0.408580,0,0.880469,0.268487
683,-0.577350,-0.092981,-0.314485,0.821365,-0.388293,0.040034,0.718933,0.297027,1,0.880469,1.126663
684,-0.577350,-0.092981,-0.314485,0.821365,-0.388293,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
685,-0.577350,-0.092981,-0.314485,0.821365,-0.388293,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
686,1.732051,-0.092981,-0.314485,-1.217485,-0.388293,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
687,-0.577350,-0.092981,-0.314485,0.821365,-0.388293,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
688,-0.577350,-0.092981,-0.314485,-1.217485,-0.388293,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
689,-0.577350,-0.092981,-0.314485,0.821365,-0.388293,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
690,-0.577350,-0.092981,-0.314485,-1.217485,-0.388293,2.348925,-0.065439,-1.349389,0,0.880469,2.843016
691,-0.577350,10.754844,-0.314485,-1.217485,-0.388293,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690
692,1.732051,-0.092981,-0.314485,-1.217485,-0.388293,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
693,1.732051,-0.092981,-0.314485,-1.217485,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
694,-0.577350,-0.092981,-0.314485,0.821365,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487
695,1.732051,-0.092981,-0.314485,-1.217485,-0.388293,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690
696,1.732051,-0.092981,-0.314485,-1.217485,-0.388293,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
697,1.732051,-0.092981,-0.314485,-1.217485,-0.388293,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690
698,-0.577350,-0.092981,-0.314485,0.821365,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
699,-0.577350,-0.092981,-0.314485,0.821365,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487

In [32]:
scaled_inputs.shape #700 observations and 14 features

(700, 11)

### split the data into train and test and shuffle

#### import relevant modules

In [33]:
from sklearn.model_selection import train_test_split

#### split

In [34]:
#splits arrays and matrices into random train and test subsets

In [35]:
train_test_split(scaled_inputs,targets)

[      Reason1    Reason2   Reason3   Reason4  Month value  \
 278  1.732051  -0.092981 -0.314485 -1.217485     0.753746
 585  1.732051  -0.092981 -0.314485 -1.217485    -1.244823
 697  1.732051  -0.092981 -0.314485 -1.217485    -0.388293
 503 -0.577350  -0.092981 -0.314485  0.821365     0.753746
 414 -0.577350  -0.092981 -0.314485  0.821365    -0.673803
 312 -0.577350  -0.092981 -0.314485 -1.217485     1.039256
 281 -0.577350  -0.092981 -0.314485  0.821365     0.753746
 616 -0.577350  -0.092981 -0.314485  0.821365    -1.244823
 441 -0.577350  -0.092981 -0.314485  0.821365    -0.102784
 183 -0.577350  -0.092981 -0.314485  0.821365    -0.959313
 286 -0.577350  -0.092981 -0.314485  0.821365     0.753746
 100 -0.577350  -0.092981 -0.314485  0.821365     1.610276
 348 -0.577350  -0.092981 -0.314485  0.821365     1.610276
 252 -0.577350  -0.092981  3.179797 -1.217485     0.468236
 69  -0.577350  -0.092981 -0.314485  0.821365     1.039256
 48  -0.577350  -0.092981 -0.314485  0.821365     0.753746
 676 -0.577350  -0.092981 -0.314485  0.821365    -0.388293
 519 -0.577350  -0.092981 -0.314485  0.821365     1.039256
 169  1.732051  -0.092981 -0.314485 -1.217485    -0.959313
 518 -0.577350  -0.092981 -0.314485  0.821365     1.039256
 368 -0.577350  -0.092981 -0.314485  0.821365    -1.530333
 350 -0.577350  -0.092981 -0.314485  0.821365     1.610276
 508  1.732051  -0.092981 -0.314485 -1.217485     1.039256
 179  1.732051  -0.092981 -0.314485 -1.217485    -0.959313
 436  1.732051  -0.092981 -0.314485 -1.217485    -0.388293
 204  1.732051  -0.092981 -0.314485 -1.217485    -0.388293
 28  -0.577350  -0.092981  3.179797 -1.217485     0.468236
 353  1.732051  -0.092981 -0.314485 -1.217485     1.610276
 1   -0.577350  -0.092981 -0.314485 -1.217485     0.182726
 419 -0.577350  -0.092981 -0.314485  0.821365    -0.673803
 ..        ...        ...       ...       ...          ...
 476 -0.577350  -0.092981 -0.314485  0.821365     0.182726
 439  1.732051  -0.092981 -0.314485 -1.217485    -0.388293
 558  1.732051  -0.092981 -0.314485 -1.217485     1.610276
 536  1.732051  -0.092981 -0.314485 -1.217485     1.324766
 455  1.732051  -0.092981 -0.314485 -1.217485    -0.102784
 83  -0.577350  -0.092981  3.179797 -1.217485     1.324766
 651  1.732051  -0.092981 -0.314485 -1.217485    -0.959313
 376 -0.577350  -0.092981 -0.314485  0.821365    -1.244823
 60  -0.577350  -0.092981 -0.314485  0.821365     0.753746
 653 -0.577350  -0.092981 -0.314485  0.821365    -0.959313
 297 -0.577350  -0.092981 -0.314485  0.821365     1.039256
 505 -0.577350  -0.092981 -0.314485  0.821365     0.753746
 316 -0.577350  -0.092981 -0.314485  0.821365     1.039256
 118 -0.577350  -0.092981 -0.314485  0.821365    -1.530333
 95  -0.577350  -0.092981 -0.314485  0.821365     1.324766
 668 -0.577350  10.754844 -0.314485 -1.217485    -0.673803
 301 -0.577350  -0.092981  3.179797 -1.217485     1.039256
 277 -0.577350  -0.092981 -0.314485 -1.217485     0.753746
 596  1.732051  -0.092981 -0.314485 -1.217485    -1.244823
 304 -0.577350  -0.092981 -0.314485  0.821365     1.039256
 228  1.732051  -0.092981 -0.314485 -1.217485    -0.102784
 335 -0.577350  10.754844 -0.314485 -1.217485     1.324766
 380 -0.577350  -0.092981 -0.314485  0.821365    -1.244823
 193 -0.577350  -0.092981 -0.314485  0.821365    -0.673803
 64  -0.577350  -0.092981 -0.314485 -1.217485     1.039256
 537 -0.577350  -0.092981 -0.314485  0.821365     1.324766
 699 -0.577350  -0.092981 -0.314485  0.821365    -0.388293
 327  1.732051  -0.092981 -0.314485 -1.217485     1.324766
 444 -0.577350  -0.092981 -0.314485  0.821365    -0.102784
 600  1.732051  -0.092981 -0.314485 -1.217485    -1.244823

      Transportation Expense       Age  Body Mass Index  Education  Children  \
 278               -0.654143  0.248310         1.002633          0 -0.919030
 585               -0.654143  0.248310         1.002633          0 -0.919030
 697                1.624567 -1.320435        -0.408580          1 -0.919030
 503                0.040034 -1.320435        -0.643782          0 -0.019280
 414                1.624567 -1.320435        -0.408580          1 -0.919030
 312                1.036026  0.562059        -0.408580          0 -0.019280
 281                1.036026  0.562059        -0.408580          0 -0.019280
 616               -0.654143  0.248310         1.002633          0 -0.919030
 441               -1.574681  0.091435         0.297027          0 -0.919030
 183                0.040034 -1.320435        -0.643782          0 -0.019280
 286                1.036026  0.562059        -0.408580          0 -0.019280
 100               -1.574681  2.130803         1.002633          0 -0.019280
 348               -0.654143 -1.006686        -1.819793          1 -0.919030
 252                1.005844 -0.536062         0.767431          0  0.880469
 69                 0.040034 -1.320435        -0.643782          0 -0.019280
 48                 0.568211 -0.065439        -0.878984          0  2.679969
 676                0.190942 -0.692937        -0.408580          1 -0.919030
 519                2.213108 -0.849811        -0.408580          0  1.780219
 169               -0.654143  0.562059        -1.114186          1  0.880469
 518                0.040034 -1.320435        -0.643782          0 -0.019280
 368               -0.654143  0.248310         1.002633          0 -0.919030
 350                0.190942  0.091435         0.532229          1 -0.019280
 508                0.190942 -0.692937        -0.408580          1 -0.919030
 179               -0.654143  0.248310         1.002633          0 -0.919030
 436                1.624567 -1.320435        -0.408580          1 -0.919030
 204                1.005844 -0.536062         0.767431          0  0.880469
 28                 1.005844 -0.536062         0.767431          0  0.880469
 353                0.190942  0.091435         0.532229          1 -0.019280
 1                 -1.574681  2.130803         1.002633          0 -0.019280
 419               -1.574681  2.130803         1.002633          0 -0.019280
 ..                      ...       ...              ...        ...       ...
 476                0.190942  1.032682         2.649049          0 -0.019280
 439                0.190942  0.091435         0.532229          1 -0.019280
 558               -0.654143 -1.006686        -1.819793          1 -0.919030
 536               -1.574681  0.091435         0.297027          0 -0.919030
 455               -0.654143  0.248310         1.002633          0 -0.919030
 83                -0.654143  0.562059        -1.114186          1  0.880469
 651               -0.654143 -1.006686        -1.819793          1 -0.919030
 376               -0.654143  0.248310         1.002633          0 -0.919030
 60                -0.654143  0.248310         1.002633          0 -0.919030
 653                2.213108 -0.849811        -0.408580          0  1.780219
 297                2.213108 -0.849811        -0.408580          0  1.780219
 505                2.213108 -0.849811        -0.408580          0  1.780219
 316               -1.574681  2.130803         1.002633          0 -0.019280
 118               -0.578689 -1.477309        -1.349389          0 -0.919030
 95                 0.040034 -1.320435        -0.643782          0 -0.019280
 668                0.190942 -0.692937        -0.408580          1 -0.919030
 301                1.005844 -0.536062         0.767431          0  0.880469
 277                1.036026 -0.692937        -0.878984          0 -0.919030
 596                0.040034 -1.320435        -0.643782          0 -0.019280
 304                0.190942  1.032682         2.649049          0 -0.019280
 228               -1.574681  2.130803         1.002633          0 -0.019280
 335                0.568211 -0.065439        -0.878984          0  2.679969
 380               -0.503235 -0.536062        -0.408580          0  0.880469
 193                1.036026  0.562059        -0.408580          0 -0.019280
 64                -1.574681  2.130803         1.002633          0 -0.019280
 537                1.005844 -0.536062         0.767431          0  0.880469
 699                1.036026  0.562059        -0.408580          0 -0.019280
 327               -1.574681  0.091435         0.297027          0 -0.919030
 444                0.040034 -1.320435        -0.643782          0 -0.019280
 600               -0.654143 -1.006686        -1.819793          1 -0.919030

          Pets
 278 -0.589690
 585 -0.589690
 697 -0.589690
 503  1.126663
 414 -0.589690
 312  0.268487
 281  0.268487
 616 -0.589690
 441 -0.589690
 183  1.126663
 286  0.268487
 100 -0.589690
 348 -0.589690
 252  0.268487
 69   1.126663
 48  -0.589690
 676 -0.589690
 519 -0.589690
 169 -0.589690
 518  1.126663
 368 -0.589690
 350  0.268487
 508 -0.589690
 179 -0.589690
 436 -0.589690
 204  0.268487
 28   0.268487
 353  0.268487
 1   -0.589690
 419 -0.589690
 ..        ...
 476 -0.589690
 439  0.268487
 558 -0.589690
 536 -0.589690
 455 -0.589690
 83  -0.589690
 651 -0.589690
 376 -0.589690
 60  -0.589690
 653 -0.589690
 297 -0.589690
 505 -0.589690
 316 -0.589690
 118 -0.589690
 95   1.126663
 668 -0.589690
 301  0.268487
 277 -0.589690
 596  1.126663
 304 -0.589690
 228 -0.589690
 335 -0.589690
 380  1.126663
 193  0.268487
 64  -0.589690
 537  0.268487
 699  0.268487
 327 -0.589690
 444  1.126663
 600 -0.589690

 [525 rows x 11 columns],
       Reason1   Reason2   Reason3   Reason4  Month value  \
 644 -0.577350 -0.092981 -0.314485  0.821365    -0.959313
 374 -0.577350 -0.092981 -0.314485  0.821365    -1.244823
 418 -0.577350 -0.092981 -0.314485  0.821365    -0.673803
 395 -0.577350 -0.092981 -0.314485  0.821365    -0.959313
 385 -0.577350 -0.092981 -0.314485  0.821365    -1.244823
 575 -0.577350 -0.092981 -0.314485  0.821365    -1.530333
 152 -0.577350 -0.092981 -0.314485  0.821365    -1.244823
 361  1.732051 -0.092981 -0.314485 -1.217485    -1.530333
 434 -0.577350 -0.092981  3.179797 -1.217485    -0.388293
 657 -0.577350 -0.092981  3.179797 -1.217485    -0.673803
 390 -0.577350 -0.092981  3.179797 -1.217485    -0.959313
 523  1.732051 -0.092981 -0.314485 -1.217485     1.039256
 548 -0.577350 -0.092981 -0.314485 -1.217485     1.324766
 584 -0.577350 -0.092981 -0.314485  0.821365    -1.530333
 462  1.732051 -0.092981 -0.314485 -1.217485     0.182726
 285 -0.577350 -0.092981 -0.314485 -1.217485     0.753746
 534  1.732051 -0.092981 -0.314485 -1.217485     1.324766
 601 -0.577350 -0.092981 -0.314485  0.821365    -1.244823
 74  -0.577350 -0.092981  3.179797 -1.217485     1.039256
 606  1.732051 -0.092981 -0.314485 -1.217485    -1.244823
 221 -0.577350 -0.092981 -0.314485  0.821365    -0.102784
 673 -0.577350 -0.092981 -0.314485  0.821365    -0.673803
 466 -0.577350 -0.092981 -0.314485  0.821365     0.182726
 113 -0.577350 -0.092981 -0.314485  0.821365    -1.530333
 46  -0.577350 -0.092981 -0.314485  0.821365     0.753746
 491 -0.577350 -0.092981 -0.314485  0.821365     0.468236
 383 -0.577350 -0.092981 -0.314485  0.821365    -1.244823
 84  -0.577350 -0.092981 -0.314485  0.821365     1.324766
 646 -0.577350 -0.092981 -0.314485  0.821365    -0.959313
 124 -0.577350 -0.092981 -0.314485  0.821365    -1.530333
 ..        ...       ...       ...       ...          ...
 172  1.732051 -0.092981 -0.314485 -1.217485    -0.959313
 140 -0.577350 -0.092981 -0.314485  0.821365    -1.244823
 480 -0.577350 -0.092981 -0.314485  0.821365     0.468236
 688 -0.577350 -0.092981 -0.314485 -1.217485    -0.388293
 631 -0.577350 -0.092981 -0.314485  0.821365    -0.959313
 452 -0.577350 -0.092981 -0.314485  0.821365    -0.102784
 638 -0.577350 -0.092981 -0.314485  0.821365    -0.959313
 126 -0.577350 -0.092981 -0.314485  0.821365    -1.530333
 683 -0.577350 -0.092981 -0.314485  0.821365    -0.388293
 167  1.732051 -0.092981 -0.314485 -1.217485    -0.959313
 560 -0.577350 -0.092981 -0.314485  0.821365     1.610276
 202  1.732051 -0.092981 -0.314485 -1.217485    -0.673803
 553 -0.577350 -0.092981 -0.314485  0.821365     1.324766
 526  1.732051 -0.092981 -0.314485 -1.217485     1.039256
 265 -0.577350 -0.092981 -0.314485  0.821365     0.468236
 561  1.732051 -0.092981 -0.314485 -1.217485     1.610276
 516 -0.577350 -0.092981 -0.314485  0.821365     1.039256
 672  1.732051 -0.092981 -0.314485 -1.217485    -0.673803
 322  1.732051 -0.092981 -0.314485 -1.217485     1.324766
 336 -0.577350 -0.092981 -0.314485 -1.217485     1.324766
 78  -0.577350 -0.092981 -0.314485  0.821365     1.039256
 43  -0.577350 -0.092981  3.179797 -1.217485     0.753746
 177  1.732051 -0.092981 -0.314485 -1.217485    -0.959313
 80  -0.577350 -0.092981 -0.314485  0.821365     1.324766
 352  1.732051 -0.092981 -0.314485 -1.217485     1.610276
 458  1.732051 -0.092981 -0.314485 -1.217485    -0.102784
 225  1.732051 -0.092981 -0.314485 -1.217485    -0.102784
 545 -0.577350 -0.092981 -0.314485  0.821365     1.324766
 460 -0.577350 -0.092981 -0.314485  0.821365     0.182726
 339  1.732051 -0.092981 -0.314485 -1.217485     1.610276

      Transportation Expense       Age  Body Mass Index  Education  Children  \
 644               -0.654143 -1.006686        -1.819793          1 -0.919030
 374               -0.654143  0.248310         1.002633          0 -0.919030
 418               -0.654143  0.248310         1.002633          0 -0.919030
 395                0.190942  0.091435         0.532229          1 -0.019280
 385               -0.654143  0.248310         1.002633          0 -0.919030
 575               -0.654143  0.562059        -1.114186          1  0.880469
 152                1.624567 -1.320435        -0.408580          1 -0.919030
 361                0.190942  0.091435         0.532229          1 -0.019280
 434                0.085306  3.385799        -1.114186          0  0.880469
 657                0.387122  1.660180         1.237836          0  0.880469
 390               -1.574681  0.091435         0.297027          0 -0.919030
 523                2.213108 -0.849811        -0.408580          0  1.780219
 548                1.036026  0.562059        -0.408580          0 -0.019280
 584               -0.654143  0.248310         1.002633          0 -0.919030
 462                0.568211 -0.065439        -0.878984          0  2.679969
 285                0.190942  1.032682         2.649049          0 -0.019280
 534                1.624567 -1.320435        -0.408580          1 -0.919030
 601               -0.654143  0.562059        -1.114186          1  0.880469
 74                 0.568211 -0.065439        -0.878984          0  2.679969
 606               -0.654143  0.248310         1.002633          0 -0.919030
 221                2.092381 -1.320435         0.061825          0 -0.019280
 673               -0.654143 -1.006686        -1.819793          1 -0.919030
 466                0.568211 -0.065439        -0.878984          0  2.679969
 113                0.040034 -1.320435        -0.643782          0 -0.019280
 46                -0.654143  0.248310         1.002633          0 -0.919030
 491                0.356940  0.718933        -0.878984          0 -0.919030
 383                1.036026  0.562059        -0.408580          0 -0.019280
 84                 1.036026  0.562059        -0.408580          0 -0.019280
 646               -0.654143  0.248310         1.002633          0 -0.919030
 124               -1.574681  0.091435         0.297027          0 -0.919030
 ..                      ...       ...              ...        ...       ...
 172                0.854936  0.405184        -0.643782          0  0.880469
 140               -1.016322 -0.379188        -0.408580          0  0.880469
 480               -0.654143  0.248310         1.002633          0 -0.919030
 688               -1.574681  2.130803         1.002633          0 -0.019280
 631               -0.654143  0.248310         1.002633          0 -0.919030
 452               -0.654143  0.248310         1.002633          0 -0.919030
 638               -0.654143  0.248310         1.002633          0 -0.919030
 126               -1.574681  0.091435         0.297027          0 -0.919030
 683                0.040034  0.718933         0.297027          1  0.880469
 167               -1.016322 -0.379188        -0.408580          0  0.880469
 560                0.040034 -1.320435        -0.643782          0 -0.019280
 202                0.190942  0.091435         0.532229          1 -0.019280
 553                2.213108 -0.849811        -0.408580          0  1.780219
 526                0.040034 -1.320435        -0.643782          0 -0.019280
 265                0.190942  0.091435         0.532229          1 -0.019280
 561                2.092381 -1.320435         0.061825          0 -0.019280
 516                2.213108 -0.849811        -0.408580          0  1.780219
 672               -1.574681  2.130803         1.002633          0 -0.019280
 322                2.348925 -0.065439        -1.349389          0  0.880469
 336                2.348925 -0.065439        -1.349389          0  0.880469
 78                 2.092381 -1.320435         0.061825          0 -0.019280
 43                 0.190942  1.032682         2.649049          0 -0.019280
 177                0.040034 -1.320435        -0.643782          0 -0.019280
 80                -0.654143  0.248310         1.002633          0 -0.919030
 352                0.190942  1.032682         2.649049          0 -0.019280
 458                1.624567 -1.320435        -0.408580          1 -0.919030
 225               -0.654143  0.248310         1.002633          0 -0.919030
 545               -1.574681  0.091435         0.297027          0 -0.919030
 460               -0.654143 -1.006686        -1.819793          1 -0.919030
 339                0.040034 -1.320435        -0.643782          0 -0.019280

          Pets
 644 -0.589690
 374 -0.589690
 418 -0.589690
 395  0.268487
 385 -0.589690
 575 -0.589690
 152 -0.589690
 361  0.268487
 434  0.268487
 657  0.268487
 390 -0.589690
 523 -0.589690
 548  0.268487
 584 -0.589690
 462 -0.589690
 285 -0.589690
 534 -0.589690
 601 -0.589690
 74  -0.589690
 606 -0.589690
 221  2.843016
 673 -0.589690
 466 -0.589690
 113  1.126663
 46  -0.589690
 491 -0.589690
 383  0.268487
 84   0.268487
 646 -0.589690
 124 -0.589690
 ..        ...
 172 -0.589690
 140 -0.589690
 480 -0.589690
 688 -0.589690
 631 -0.589690
 452 -0.589690
 638 -0.589690
 126 -0.589690
 683  1.126663
 167 -0.589690
 560  1.126663
 202  0.268487
 553 -0.589690
 526  1.126663
 265  0.268487
 561  2.843016
 516 -0.589690
 672 -0.589690
 322  2.843016
 336  2.843016
 78   2.843016
 43  -0.589690
 177  1.126663
 80  -0.589690
 352 -0.589690
 458 -0.589690
 225 -0.589690
 545 -0.589690
 460 -0.589690
 339  1.126663

 [175 rows x 11 columns],
 array([1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
        1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
        0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
        0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
        1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
        1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
        1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,

In [36]:
# array1: training dataset with inputs
# array2: training dataset with targets
# array3: testing dataset with inputs
# array4: testing dataset with targets

In [37]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets, train_size=0.8,random_state=20)

In [38]:
print(x_train.shape,y_train.shape)
# this means inputs contains 525 observations along 14 features
#targets are vector of length 525

(560, 11) (560,)

In [39]:
print(x_test.shape,y_test.shape)

(140, 11) (140,)

In [40]:
#usually opt for splits like 80-20 or 90-10(because we want to train on more data)
#initially got 525 and 175 of 700 means....>got 75-25 split
#to change the split.....> train size and shuffle
#train size can take values between 0 and 1
#by default shuffle is set to true
#sklearn.model_selection.train_test_split(inputs,targets,train_size,shuffle,random_state)
#random state parameter takes integer values. assigning new number will make shuffle pseudo random...
#...in this way the method will always shuffle the observations in same random way
#after setting trainsize=0.8 and randon state=20, got 80-20 split of data

### logistic regression with sklearn

#### import relevant libraries

In [41]:
from sklearn.linear_model import LogisticRegression #since we are using logistic regression
from sklearn import metrics #quite useful in evaluating the model

#### training the model

In [42]:
reg=LogisticRegression()
reg.fit(x_train,y_train)

C:\Users\lavy_\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [43]:
#evaluate model accuracy using score method
#got 0.78 means 80% accuracy with this model
reg.score(x_train,y_train)

0.7875

#### manually check the accuracy

In [44]:
#accuracy means x% of the model output matches the targets
#80% accuracy means logistic regression model output matches 80% of the targets

In [45]:
#if you want to find accuracy manually, we should find outputs and compare them with targets
#inorder to find model outputs use sklearn method 'predict'

In [46]:
model_outputs=reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0])

In [47]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [48]:
#above two arrays may lookalike but they are different
#its hard to see the difference with naked eye so use code

In [49]:
model_outputs==y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False,  True,  True, False,  True, False,  True,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True])

In [50]:
#now can see which elements guessed correctly which aren't but how many are there
#true=1 false=0 could use numpy 'sum' method

In [51]:
np.sum(model_outputs==y_train) #total no.of correct predictions(true entries)

441

In [52]:
model_outputs.shape[0] # no.of observations

560

In [53]:
#accuracy=correct no.of predictions/ no.of observations

In [54]:
np.sum(model_outputs==y_train)/model_outputs.shape[0]

0.7875

### finding the intercept and coefficents

In [55]:
reg.intercept_  #intercept

array([-0.16924304])

In [56]:
reg.coef_  #coefficients

array([[ 2.0674645 ,  0.33437476,  1.55990772,  1.31151248,  0.18510535,
         0.69063727, -0.19799436,  0.32749477, -0.31577027,  0.37190506,
        -0.32452824]])

### sklearn methods are compatible with pandas dataframes
### whenever you employ sklearn, results are arrays, not dataframes
### sklearn results are in--------->arrays (need to learn both arrays and dataframes)
### statmodels results are in------>dataframes

In [57]:
#extracting column values of unscaled_inputs
unscaled_inputs.columns.values

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [58]:
feature_name=unscaled_inputs.columns.values

### making dataframe of featurename and coefficient

In [59]:
summary_table=pd.DataFrame(columns=['feature_name'],data=feature_name)

In [60]:
#by default numpy arrays are rows not columns
summary_table['coefficient']=np.transpose(reg.coef_)
summary_table

              feature_name  coefficient
0                  Reason1     2.067464
1                  Reason2     0.334375
2                  Reason3     1.559908
3                  Reason4     1.311512
4              Month value     0.185105
5   Transportation Expense     0.690637
6                      Age    -0.197994
7          Body Mass Index     0.327495
8                Education    -0.315770
9                 Children     0.371905
10                    Pets    -0.324528

In [61]:
#adding intercept as row to summary table

In [62]:
summary_table.index=summary_table.index+1 #shift index values from 0-13 to 1-14
summary_table.loc[0]=['intercept',reg.intercept_[0]] #adding intercept as index 0
summary_table=summary_table.sort_index() #sort the dataframe by index
summary_table

              feature_name  coefficient
0                intercept    -0.169243
1                  Reason1     2.067464
2                  Reason2     0.334375
3                  Reason3     1.559908
4                  Reason4     1.311512
5              Month value     0.185105
6   Transportation Expense     0.690637
7                      Age    -0.197994
8          Body Mass Index     0.327495
9                Education    -0.315770
10                Children     0.371905
11                    Pets    -0.324528

### interpreting the coefficients

In [63]:
#coefficients are called weights and intercept called bias
#the closer coefficient to the 0 the smaller weight it is
#the farther coefficient to the 0, no matter it is positive or negative,the higher weight
#this is true for only for coefficients that are of the same scale
#standardized coefficients are basically coefficients of regression where all variable have been standardized
#whichever weight is bigger its corresponding feature is more important

In [64]:
summary_table['odds ratio']=np.exp(summary_table.coefficient)

In [65]:
summary_table

              feature_name  coefficient  odds ratio
0                intercept    -0.169243    0.844304
1                  Reason1     2.067464    7.904755
2                  Reason2     0.334375    1.397067
3                  Reason3     1.559908    4.758382
4                  Reason4     1.311512    3.711783
5              Month value     0.185105    1.203345
6   Transportation Expense     0.690637    1.994986
7                      Age    -0.197994    0.820374
8          Body Mass Index     0.327495    1.387488
9                Education    -0.315770    0.729227
10                Children     0.371905    1.450495
11                    Pets    -0.324528    0.722868

In [66]:
summary_table.sort_values('odds ratio',ascending=False)

              feature_name  coefficient  odds ratio
1                  Reason1     2.067464    7.904755
3                  Reason3     1.559908    4.758382
4                  Reason4     1.311512    3.711783
6   Transportation Expense     0.690637    1.994986
10                Children     0.371905    1.450495
2                  Reason2     0.334375    1.397067
8          Body Mass Index     0.327495    1.387488
5              Month value     0.185105    1.203345
0                intercept    -0.169243    0.844304
7                      Age    -0.197994    0.820374
9                Education    -0.315770    0.729227
11                    Pets    -0.324528    0.722868

In [67]:
#if a coefficient is around 0 and odds ratio is around 1 that feature is not particularly important

### test the model

In [68]:
reg.score(x_test,y_test)

0.7357142857142858

In [ ]:
#so based on data that model has never seen before, 
#73.6% of the cases the model will predict correctly if the person is excessively absent.
#test accuracy is always less than train accuracy by definition
#often test accuracy is 10%-20% lessthan train accuracy due to overfitting
#in this case, only 4% difference so model is good to go
#we can get outputs manually......using 'predict' method

In [69]:
model_outputs=reg.predict(x_train) # manually predicting outputs
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0])

In [70]:
#instead of getting 0 and 1, we can get 'probability' of being 0 and 1 using 'predict_proba'

In [75]:
predicted_proba=reg.predict_proba(x_test)
predicted_proba

array([[0.70787875, 0.29212125],
       [0.57240632, 0.42759368],
       [0.39722156, 0.60277844],
       [0.7871614 , 0.2128386 ],
       [0.06706237, 0.93293763],
       [0.31158323, 0.68841677],
       [0.28623871, 0.71376129],
       [0.08098094, 0.91901906],
       [0.7998164 , 0.2001836 ],
       [0.74960402, 0.25039598],
       [0.46775646, 0.53224354],
       [0.1847786 , 0.8152214 ],
       [0.04107863, 0.95892137],
       [0.75155043, 0.24844957],
       [0.23838403, 0.76161597],
       [0.53708693, 0.46291307],
       [0.53372215, 0.46627785],
       [0.52054949, 0.47945051],
       [0.40619764, 0.59380236],
       [0.0276527 , 0.9723473 ],
       [0.70196092, 0.29803908],
       [0.7871614 , 0.2128386 ],
       [0.40618889, 0.59381111],
       [0.40618889, 0.59381111],
       [0.17505998, 0.82494002],
       [0.75415565, 0.24584435],
       [0.48882312, 0.51117688],
       [0.87893898, 0.12106102],
       [0.13105335, 0.86894665],
       [0.7871614 , 0.2128386 ],
       [0.62318131, 0.37681869],
       [0.30551352, 0.69448648],
       [0.28937391, 0.71062609],
       [0.44155533, 0.55844467],
       [0.7871614 , 0.2128386 ],
       [0.43666343, 0.56333657],
       [0.79122047, 0.20877953],
       [0.1908699 , 0.8091301 ],
       [0.58605681, 0.41394319],
       [0.37002999, 0.62997001],
       [0.79588133, 0.20411867],
       [0.57556396, 0.42443604],
       [0.77322277, 0.22677723],
       [0.89490845, 0.10509155],
       [0.14238844, 0.85761156],
       [0.34680759, 0.65319241],
       [0.29444083, 0.70555917],
       [0.70787875, 0.29212125],
       [0.78901666, 0.21098334],
       [0.80433282, 0.19566718],
       [0.43124962, 0.56875038],
       [0.9207552 , 0.0792448 ],
       [0.31158323, 0.68841677],
       [0.73143429, 0.26856571],
       [0.14076491, 0.85923509],
       [0.54636067, 0.45363933],
       [0.06986026, 0.93013974],
       [0.78237554, 0.21762446],
       [0.9139322 , 0.0860678 ],
       [0.90968309, 0.09031691],
       [0.2910067 , 0.7089933 ],
       [0.32303071, 0.67696929],
       [0.712922  , 0.287078  ],
       [0.14010368, 0.85989632],
       [0.81017561, 0.18982439],
       [0.72924644, 0.27075356],
       [0.98600451, 0.01399549],
       [0.79122047, 0.20877953],
       [0.1888082 , 0.8111918 ],
       [0.71002404, 0.28997596],
       [0.79122047, 0.20877953],
       [0.93149222, 0.06850778],
       [0.07105918, 0.92894082],
       [0.52084814, 0.47915186],
       [0.36081904, 0.63918096],
       [0.7871614 , 0.2128386 ],
       [0.15018779, 0.84981221],
       [0.25988275, 0.74011725],
       [0.23069089, 0.76930911],
       [0.320897  , 0.679103  ],
       [0.76382211, 0.23617789],
       [0.98839147, 0.01160853],
       [0.78237554, 0.21762446],
       [0.22374502, 0.77625498],
       [0.55494762, 0.44505238],
       [0.89969303, 0.10030697],
       [0.26813106, 0.73186894],
       [0.40618889, 0.59381111],
       [0.94847576, 0.05152424],
       [0.30551352, 0.69448648],
       [0.85354048, 0.14645952],
       [0.86135416, 0.13864584],
       [0.77817277, 0.22182723],
       [0.72924644, 0.27075356],
       [0.74960402, 0.25039598],
       [0.12631464, 0.87368536],
       [0.69683141, 0.30316859],
       [0.2147196 , 0.7852804 ],
       [0.76141629, 0.23858371],
       [0.80931223, 0.19068777],
       [0.3368173 , 0.6631827 ],
       [0.30551352, 0.69448648],
       [0.28086659, 0.71913341],
       [0.23962312, 0.76037688],
       [0.53401994, 0.46598006],
       [0.49443575, 0.50556425],
       [0.71868604, 0.28131396],
       [0.12631464, 0.87368536],
       [0.20392803, 0.79607197],
       [0.86754591, 0.13245409],
       [0.98954368, 0.01045632],
       [0.07489017, 0.92510983],
       [0.25159304, 0.74840696],
       [0.65962456, 0.34037544],
       [0.44970439, 0.55029561],
       [0.42050748, 0.57949252],
       [0.14660706, 0.85339294],
       [0.15445355, 0.84554645],
       [0.45717576, 0.54282424],
       [0.69078754, 0.30921246],
       [0.73955407, 0.26044593],
       [0.86103015, 0.13896985],
       [0.14823037, 0.85176963],
       [0.57556396, 0.42443604],
       [0.7871614 , 0.2128386 ],
       [0.65277369, 0.34722631],
       [0.79588133, 0.20411867],
       [0.90459689, 0.09540311],
       [0.22872524, 0.77127476],
       [0.70196092, 0.29803908],
       [0.35779726, 0.64220274],
       [0.79588133, 0.20411867],
       [0.69683141, 0.30316859],
       [0.65277369, 0.34722631],
       [0.74424804, 0.25575196],
       [0.44970439, 0.55029561],
       [0.52054949, 0.47945051],
       [0.69902333, 0.30097667],
       [0.76141629, 0.23858371],
       [0.52084814, 0.47915186]])

In [78]:
#the first column shows probability that model assigned to the observation being 0 and 
#second column shows probability that model assigned to the observation being 1

In [76]:
predicted_proba.shape

(140, 2)

In [79]:
#in this case, need to focus on probability of excessive absenteeism...so focus on probability of being 1
#slice the second column of predicted_proba

In [81]:
predicted_proba[:,1] #predicted_proba second column(probability of observation being 1)

array([0.29212125, 0.42759368, 0.60277844, 0.2128386 , 0.93293763,
       0.68841677, 0.71376129, 0.91901906, 0.2001836 , 0.25039598,
       0.53224354, 0.8152214 , 0.95892137, 0.24844957, 0.76161597,
       0.46291307, 0.46627785, 0.47945051, 0.59380236, 0.9723473 ,
       0.29803908, 0.2128386 , 0.59381111, 0.59381111, 0.82494002,
       0.24584435, 0.51117688, 0.12106102, 0.86894665, 0.2128386 ,
       0.37681869, 0.69448648, 0.71062609, 0.55844467, 0.2128386 ,
       0.56333657, 0.20877953, 0.8091301 , 0.41394319, 0.62997001,
       0.20411867, 0.42443604, 0.22677723, 0.10509155, 0.85761156,
       0.65319241, 0.70555917, 0.29212125, 0.21098334, 0.19566718,
       0.56875038, 0.0792448 , 0.68841677, 0.26856571, 0.85923509,
       0.45363933, 0.93013974, 0.21762446, 0.0860678 , 0.09031691,
       0.7089933 , 0.67696929, 0.287078  , 0.85989632, 0.18982439,
       0.27075356, 0.01399549, 0.20877953, 0.8111918 , 0.28997596,
       0.20877953, 0.06850778, 0.92894082, 0.47915186, 0.63918096,
       0.2128386 , 0.84981221, 0.74011725, 0.76930911, 0.679103  ,
       0.23617789, 0.01160853, 0.21762446, 0.77625498, 0.44505238,
       0.10030697, 0.73186894, 0.59381111, 0.05152424, 0.69448648,
       0.14645952, 0.13864584, 0.22182723, 0.27075356, 0.25039598,
       0.87368536, 0.30316859, 0.7852804 , 0.23858371, 0.19068777,
       0.6631827 , 0.69448648, 0.71913341, 0.76037688, 0.46598006,
       0.50556425, 0.28131396, 0.87368536, 0.79607197, 0.13245409,
       0.01045632, 0.92510983, 0.74840696, 0.34037544, 0.55029561,
       0.57949252, 0.85339294, 0.84554645, 0.54282424, 0.30921246,
       0.26044593, 0.13896985, 0.85176963, 0.42443604, 0.2128386 ,
       0.34722631, 0.20411867, 0.09540311, 0.77127476, 0.29803908,
       0.64220274, 0.20411867, 0.30316859, 0.34722631, 0.25575196,
       0.55029561, 0.47945051, 0.30097667, 0.23858371, 0.47915186])

In [82]:
#in reality logistic regression model calculate these probabilities in the background
#if the probability is lessthan 0.5 model places a 0
#if the probability is greaterthan 0.5 model places a 1

### save the model

In [90]:
#there are several ways to save model, here 'pickle' is used to save the model
#pickle is a python module to convert python object into a character stream
#this means will save 'reg' variable into a file
#reg file pickled as model

In [91]:
import pickle
with open('model','wb')as file:
    pickle.dump(reg,file)

In [92]:
# filename = model
# write bytes = wb (pickle(save) the file use 'wb' and unpickle(extract) the file using 'rb')
# pickle (save) the file with 'dump'
# unpickle (extract) the file with 'load'

In [93]:
#absenteeism_scaler is used to standardize all numerical valuables so it should be saved to
#absenteeism_scaler pickled as scaler

In [94]:
with open('scaler','wb')as file:
    pickle.dump(absenteeism_scaler,file)